name: Train Machine Learning Model

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pandas scikit-learn matplotlib seaborn

      - name: Run ML code
        run: |
          python script.py

      - name: Save results
        run: |
          cp results.txt actual_vs_predicted.png 


